### ISSUE TITLE
Enhance Install / ZIP section of chocolateyinstall.ps1 and make config.yml sections optional to include

### ISSUE THREAD

**Issue by marty-sullivan** [CU-CommunityApps/choco-packages#7]
Right now, the Install section is pretty limited. It just downloads and extracts the ZIP from S3 via `Install-ChocolateyZipPackage` and runs the specified exe/msi/msu via `Install-ChocolateyInstallPackage` with the arguments specified in config.yml. The following enhancements are needed:

- Silently install more than one EXE per package
    - Enable specification of one or many setup EXEs that are invoked by `Install-ChocolateyInstallPackage`
- One ZIP in S3 per package
    - Essentially, the script should run `Install-ChocolateyZipPackage` and then loop through and install one or more exe/msi/msu that are inside the ZIP with `Install-ChocolateyInstallPackage`
- Make config.yml sections optional to include
    - Rather than having to set a section to null or an empty array/map, chocolateyinstall.ps1 should just check if the section/sub-section exists. 
    - For example, no reason to have Registry section if no registry keys are set. No reason to list every Hive if only one key/property is being set in a single Hive.
    - This will make config.yml much easier to write and also less cluttered to read

https://github.com/CU-CommunityApps/choco-packages/blob/0e42d069548e1c911504c2f5616dd8c3c6237be2/bootstrap/templates/chocolateyinstall.ps1#L56-L101

**Comment by dpk25** [comment]
enhancements added to Dev and Test

**Comment by dpk25** [comment]
Enhancements added as requested, pending master merge.
